### ISSUE TITLE
Running freesound on Windows, setting up database, ProgrammingError: relation "forum_thread" does not exist, populating db without dump?

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1245]
I'm trying to follow https://github.com/MTG/freesound/wiki/Development-setup on Windows, skipping optional stuff. I came as far as running the site but visiting it leads to this:

```
Unable to process log entry: Unsupported Sentry DSN scheme:  (DSN_PROVIDED_BY_SENTRY)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\contrib\django\models.py", line 175, in sentry_exception_handler
    client.captureException(exc_info=sys.exc_info(), request=request)
  File "C:\Python27\lib\site-packages\raven\contrib\django\models.py", line 54, in <lambda>
    __getattr__ = lambda x, o: getattr(get_client(), o)
  File "C:\Python27\lib\site-packages\raven\contrib\django\models.py", line 155, in get_client
    instance = Client(**options)
  File "C:\Python27\lib\site-packages\raven\base.py", line 145, in __init__
    self.set_dsn(dsn, transport)
  File "C:\Python27\lib\site-packages\raven\base.py", line 200, in set_dsn
    transport_registry=self._registry,
  File "C:\Python27\lib\site-packages\raven\conf\remote.py", line 75, in from_string
    raise InvalidDsn(ERR_UNKNOWN_SCHEME.format(url.scheme, value))
InvalidDsn: Unsupported Sentry DSN scheme:  (DSN_PROVIDED_BY_SENTRY)
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Download\freesound\sounds\views.py", line 178, in front_page
    current_forum_threads = Thread.objects.filter(pk__in=get_current_thread_ids(),
  File "E:\Download\freesound\sounds\views.py", line 171, in get_current_thread_ids
    """)
  File "C:\Python27\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 165, in execute
    return self._record(self.cursor.execute, sql, params)
  File "C:\Python27\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 107, in _record
    return method(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 63, in execute
    return self.cursor.execute(sql)
ProgrammingError: relation "forum_thread" does not exist
LINE 3:             FROM forum_thread, forum_post
                         ^
```

I'm not sure whether I installed SOLR properly. I had to comment out `'dsn': 'DSN_PROVIDED_BY_SENTRY',` in local_settings.py.

Trying to run `python manage.py reindex_solr` leads to
```
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\raven\contrib\django\management\__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "E:\Download\freesound\search\management\commands\reindex_solr.py", line 47, in handle
    console_logger.info("Reindexing %d sounds to solr", sounds_to_index.count())
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "sounds_sound" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "sounds_sound" WHERE ("sou...
```

I think the solution to this issue is to either get a privacy-nonproblematic dump file for filling up the database or finding out how to fill it up with the necessary tables(?).

Would there happen to be a `python manage.py dummy_data` command or something? I can't remember at all what I did when I set this up years ago on Linux.

**Comment by bdejong** [comment]
Hi Iwan!

Could you try running
`python manage.py migrate`
and see if that creates the database and tables?

I think the wiki guide hasn't been updated in ... forever.

Bram

**Comment by qubodup** [comment]
Hi Bram,

It worked!!!

The site runs now. Search reports "There was an error while searching, is your query correct?" (I paid very little attention when setting up Solr) but I can reach and test the parts of the website that I hope to be able to provide small fixes for.

Thank you!

**Comment by bdejong** [comment]
Perhaps you could change the wiki to match what you did?

**Comment by qubodup** [comment]
Sure, I'll add the info about proceeding without a dump and write a note about Windows.
