### ISSUE TITLE
Approving any sound results in 500 error

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1772]
Approving any sound in Chrome currently results in a 500 error:

![image](https://github.com/MTG/freesound/assets/18312/8ebf8e55-be06-4a81-a3d3-6f7a7c62e8c9)

The sound does get approved however.

I tried logging out and in and I tried it in incognito mode. Same results.

Below are two error messages, the bottom one might be a separate error of the error page.

```
71257/:1        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:810 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at s (index.js:810:570)
    at parcelRequire.cYDc.../utils/cookies (index.js:884:140)
    at u (index.js:1:466)
    at p (index.js:1:542)
    at parcelRequire.8/iA../asyncSection (index.js:907:40)
    at u (index.js:1:466)
    at p (index.js:1:542)
    at parcelRequire.Focm.core-js/stable (index.js:911:217)
    at u (index.js:1:466)
    at parcelRequire.AQ65 (index.js:1:765)
```

**Comment by ffont** [comment]
It could probably be a temporary issue, I saw a couple of errors in the servers as well. Can you try again?
